version: 2
jobs:
  pull:
    machine: true
    steps:
      - checkout
      - run: docker pull ghostofcookie/gofish:latest
  build:
    machine: true
    requires: 
      - pull
    steps:
      # Need to build docker image from newly updated code.
      - run: docker run ghostofcookie/gofish:latest /bin/sh /goFish/build
      - run: docker run ghostofcookie/gofish:latest /bin/sh /goFish/run_tests
  push:
    machine: true
    requires: 
      - build
    steps:
      - run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run: docker push ghostofcookie/gofish:latest